"""TinyAgent Python.

A small agent framework for building LLM-powered applications.
"""

from .agent import Agent, AgentOptions, default_convert_to_llm, extract_text
from .agent_loop import (
    agent_loop,
    agent_loop_continue,
    create_agent_stream,
    stream_assistant_response,
    stream_simple,
)
from .agent_tool_execution import (
    execute_tool_calls,
    skip_tool_call,
    validate_tool_arguments,
)
from .agent_types import (
    AfterToolCallFn,
    AgentContext,
    AgentEndEvent,
    AgentEvent,
    AgentLoopConfig,
    AgentMessage,
    AgentStartEvent,
    AgentState,
    AgentTool,
    AgentToolResult,
    AgentToolUpdateCallback,
    AssistantMessage,
    AssistantMessageEvent,
    BeforeToolCallFn,
    Context,
    CustomAgentMessage,
    EventStream,
    ImageContent,
    Message,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    Model,
    ShouldStopAfterTurnFn,
    SimpleStreamOptions,
    StreamFn,
    StreamResponse,
    TextContent,
    ThinkingLevel,
    Tool,
    ToolCall,
    ToolCallContent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    ToolLoopControl,
    ToolResultMessage,
    TurnEndEvent,
    TurnStartEvent,
    UserMessage,
)
from .proxy import ProxyStreamOptions, ProxyStreamResponse, create_proxy_stream, stream_proxy
from .proxy_event_handlers import parse_streaming_json

__all__ = [
    # Agent
    "Agent",
    "AgentOptions",
    "default_convert_to_llm",
    "extract_text",
    # Agent loop
    "agent_loop",
    "agent_loop_continue",
    "create_agent_stream",
    "stream_assistant_response",
    "stream_simple",
    # Tool execution
    "execute_tool_calls",
    "skip_tool_call",
    "validate_tool_arguments",
    # Types
    "ThinkingLevel",
    "TextContent",
    "ImageContent",
    "ToolCall",
    "ToolCallContent",
    "UserMessage",
    "AssistantMessage",
    "ToolResultMessage",
    "CustomAgentMessage",
    "Message",
    "AgentMessage",
    "AgentToolResult",
    "ToolLoopControl",
    "Tool",
    "AgentTool",
    "AgentToolUpdateCallback",
    "Context",
    "AgentContext",
    "Model",
    "SimpleStreamOptions",
    "AssistantMessageEvent",
    "StreamResponse",
    "AgentStartEvent",
    "AgentEndEvent",
    "TurnStartEvent",
    "TurnEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "MessageEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolExecutionEndEvent",
    "AgentEvent",
    "AgentLoopConfig",
    "AgentState",
    "EventStream",
    "StreamFn",
    "BeforeToolCallFn",
    "AfterToolCallFn",
    "ShouldStopAfterTurnFn",
    # Proxy
    "ProxyStreamOptions",
    "ProxyStreamResponse",
    "stream_proxy",
    "create_proxy_stream",
    "parse_streaming_json",
]
